unbind r
bind r source-file ~/.tmux.conf

unbind %
unbind '"'
unbind z

# Muda o prefixo do tmux
set -g prefix C-x

# Habilita o mouse
set -g mouse on

# Atalhos
bind-key h select-pane -L # Selecionar painel a esquerda
bind-key j select-pane -D # Selecionar painal a direita 
bind-key k select-pane -U # Selecionar painel acima
bind-key l select-pane -R # Selecionar painel em baixo
bind-key m resize-pane -Z # Maximizar painel
bind | split-window -h -c "#{pane_current_path}" # Dividir painel ao lado (vertical) com a tecla |
bind - split-window -v -c "#{pane_current_path}" # Dividir painel abaixo (horizontal) com a tecla -
bind C-w kill-window # Fechar a janela atual

# Lista de plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'niksingh710/minimal-tmux-status'
set -g @plugin 'tmux-plugins/tmux-resurrect'

#### Minimal tmux status ####
set -g @minimal-tmux-fg "#000000"
set -g @minimal-tmux-bg "#698DDA"
set -g @minimal-tmux-justify "centre"
set -g @minimal-tmux-indicator-str "  tmux  "
set -g @minimal-tmux-indicator true
set -g @minimal-tmux-status "top"

set -g @minimal-tmux-right true
set -g @minimal-tmux-left true

set -g @minimal-tmux-expanded-icon "󰊓 "

set -g @minimal-tmux-show-expanded-icon-for-all-tabs true

set -g @minimal-tmux-status-right-extra ""
set -g @minimal-tmux-status-left-extra ""

set -g @minimal-tmux-use-arrow true
set -g @minimal-tmux-right-arrow ""
set -g @minimal-tmux-left-arrow ""

set -g @minimal-tmux-status-right "#S"

set -g status-right-length 20
set -g status-left-length 20

# Inicializa o TPM
run '~/.tmux/plugins/tpm/tpm'
